import { grossByMember, grossByMonth, kpis, unitsByCategory, unitsByLocation } from '../domain/selectors';
import { monthLabel } from '../domain/dates';
import type { InsightRequest, InsightResponse, InsightsProvider } from './InsightsProvider';
import type { Scope } from '../domain/types';

const usd = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n);
const num = (n: number) => new Intl.NumberFormat('en-US').format(n);
export const FALLBACK = 'I can answer questions about the sales shown on this dashboard: top location, best-selling category, team leader board, month-over-month change and average order value.';

/** Deterministic sample provider: answers are computed from the current session's demo data, not generated by a model. */
export class SampleInsightsProvider implements InsightsProvider {
  readonly label = 'Sample response · computed from demo data';
  constructor(private readonly delayMs = 400) {}

  suggestions(scope: Scope): string[] {
    const base = ['Best-selling category', 'Compare this month to last month', 'Average order value'];
    if (scope.kind === 'company') return ['Top location by units', ...base];
    if (scope.kind === 'team') return ['Who leads the team?', ...base];
    return base;
  }

  answer(req: InsightRequest, signal: AbortSignal): Promise<InsightResponse> {
    return new Promise((resolve, reject) => {
      const t = setTimeout(() => resolve(this.compute(req)), this.delayMs);
      signal.addEventListener('abort', () => { clearTimeout(t); reject(new DOMException('Cancelled', 'AbortError')); }, { once: true });
    });
  }

  compute({ prompt, scope, scopeLabel, data, now }: InsightRequest): InsightResponse {
    const p = prompt.toLowerCase();
    if (/location|state|store|region|outlet/.test(p)) {
      const rows = unitsByLocation(data, scope, now).sort((a, b) => b.value - a.value);
      const total = rows.reduce((s, r) => s + r.value, 0) || 1;
      const top = rows[0];
      return { kind: 'sample', text: `**${top.label}** leads ${scopeLabel} with ${num(top.value)} units (${Math.round((top.value / total) * 100)}% of the last 12 months). Next: ${rows.slice(1).map((r) => `${r.label} ${num(r.value)}`).join(', ')}.`, evidence: rows.map((r) => ({ selector: 'unitsByLocation', key: r.key, value: r.value })) };
    }
    if (/categor|product|sell/.test(p)) {
      const rows = unitsByCategory(data, scope, now).sort((a, b) => b.value - a.value);
      return { kind: 'sample', text: `The best-selling category for ${scopeLabel} is **${rows[0].label}** with ${num(rows[0].value)} units, followed by ${rows[1].label} (${num(rows[1].value)}). ${rows[rows.length - 1].label} sells least (${num(rows[rows.length - 1].value)}).`, evidence: rows.map((r) => ({ selector: 'unitsByCategory', key: r.key, value: r.value })) };
    }
    if (/lead|top rep|best rep|member|who/.test(p)) {
      if (scope.kind !== 'team') return { kind: 'sample', text: 'Switch the privilege to **Team Lead** to compare team members.', evidence: [] };
      const rows = grossByMember(data, scope.leadId, now).sort((a, b) => b.value - a.value);
      return { kind: 'sample', text: `**${rows[0].label}** leads the team with ${usd(rows[0].value)} in gross sales. ${rows.slice(1).map((r) => `${r.label}: ${usd(r.value)}`).join('; ')}.`, evidence: rows.map((r) => ({ selector: 'grossByMember', key: r.key, value: r.value })) };
    }
    if (/month|trend|compare|last/.test(p)) {
      const rows = grossByMonth(data, scope, now);
      const cur = rows[rows.length - 1]; const prev = rows[rows.length - 2];
      const day = now.getDate();
      const change = prev.value ? Math.round(((cur.value - prev.value) / prev.value) * 100) : 0;
      return { kind: 'sample', text: `${monthLabel(cur.key)} so far (${day} days): ${usd(cur.value)} for ${scopeLabel}. ${monthLabel(prev.key)} closed at ${usd(prev.value)}${prev.value ? ` — ${change >= 0 ? '+' : ''}${change}% so far versus the full previous month` : ''}.`, evidence: [cur, prev].map((r) => ({ selector: 'grossByMonth', key: r.key, value: r.value })) };
    }
    if (/average|aov|order value|basket/.test(p)) {
      const k = kpis(data, scope, now);
      return { kind: 'sample', text: `Average order value for ${scopeLabel} is **${usd(k.avgOrderValue)}** across ${num(k.orders)} orders (${usd(k.gross)} gross, last 12 months).`, evidence: [{ selector: 'kpis', key: 'avgOrderValue', value: k.avgOrderValue }] };
    }
    return { kind: 'sample', text: FALLBACK, evidence: [] };
  }
}
