import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { FabComponent } from '@syncfusion/ej2-react-buttons';
import { SidebarComponent } from '@syncfusion/ej2-react-navigations';
import { AppLoading } from '../components/AppLoading';
import { useSalesStore } from '../../state/SalesStore';
import { useViewState } from '../viewState';
import { fullName } from '../../domain/selectors';

// The AI AssistView and its conversation load on first open, not with the first page.
const AssistantPanel = lazy(() => import('./AssistantPanel'));

const FAB_ID = 'assistant-fab';
const PANEL_ID = 'assistant-panel';

/**
 * AI Assist on every page: a Syncfusion Floating Action Button at the bottom right opens a right-side
 * Syncfusion Sidebar holding the AI AssistView. The same button stays in place and becomes the close
 * button while the panel is open; Escape closes it too. `resetCount` changes when the demo data is reset,
 * which starts a new conversation.
 */
export function AssistantHost({ resetCount }: { resetCount: number }) {
  const [open, setOpen] = useState(false);
  const [everOpened, setEverOpened] = useState(false);
  const { data } = useSalesStore();
  const { privilege, leadId, repId, scope } = useViewState();

  const person = (id: number) => { const e = data?.employees.find((x) => x.id === id); return e ? fullName(e) : 'Unknown'; };
  const scopeLabel = privilege === 'SM' ? 'the company' : privilege === 'TL' ? `${person(leadId)}'s team` : person(repId);
  const viewLabel = privilege === 'SM' ? 'Sales Manager view' : privilege === 'TL' ? `Team Lead view · ${person(leadId)}` : `Sales Rep view · ${person(repId)}`;

  const hide = useCallback((returnFocus: boolean) => {
    setOpen(false);
    if (returnFocus) document.getElementById(FAB_ID)?.focus();
  }, []);
  // Syncfusion keeps the click handler from the first render, so it reads the current state through a ref.
  const openRef = useRef(open);
  openRef.current = open;
  const toggle = useCallback(() => {
    if (openRef.current) hide(true);
    else { setEverOpened(true); setOpen(true); }
  }, [hide]);

  // The button is drawn by Syncfusion; name its current action and tie it to the panel for assistive
  // technology. The stylesheet swaps the chat icon for the close icon on aria-expanded.
  useEffect(() => {
    const fab = document.getElementById(FAB_ID);
    if (!fab) return;
    const label = open ? 'Close AI Assist' : 'Open AI Assist';
    fab.setAttribute('aria-label', label);
    fab.setAttribute('title', label);
    fab.setAttribute('aria-controls', PANEL_ID);
    fab.setAttribute('aria-expanded', String(open));
  });

  // Opening moves focus to the prompt box (once the view has loaded). Escape closes the panel from
  // anywhere on the page, unless something on top of it (a dialog, a popup list) has already used the key.
  useEffect(() => {
    if (!open) return;
    let tries = 0;
    const focusPrompt = () => {
      const box = document.querySelector<HTMLElement>(`#${PANEL_ID} .e-footer textarea, #${PANEL_ID} .e-footer [contenteditable="true"]`);
      if (box) box.focus();
      else if (++tries < 40) timer = window.setTimeout(focusPrompt, 100);
    };
    let timer = window.setTimeout(focusPrompt, 100);
    const onKey = (event: KeyboardEvent) => {
      if (event.key !== 'Escape' || event.defaultPrevented) return;
      if (document.querySelector('.e-dialog.e-popup-open, .e-popup.e-popup-open')) return;
      hide(true);
    };
    document.addEventListener('keydown', onKey);
    return () => { window.clearTimeout(timer); document.removeEventListener('keydown', onKey); };
  }, [open, hide]);

  return (
    <>
      <FabComponent id={FAB_ID} iconCss="assistant-fab-icon" position="BottomRight" onClick={toggle} />
      {/* Not navigation, so nothing to dock to: enableDock is off on purpose (the navigation Sidebar docks).
          No `target` and no `className`; styled by id. */}
      <SidebarComponent id={PANEL_ID} position="Right" type="Over" width="400px" isOpen={open} enableDock={false}
        showBackdrop={false} closeOnDocumentClick={false} enableGestures={false} zIndex={1002}
        close={() => setOpen(false)} open={() => setOpen(true)}>
        <section className="assistant" aria-label="AI Assist">
          <header className="assistant-header">
            <h2>AI Assist</h2>
            <span className="sample-badge">Sample</span>
          </header>
          <p className="assistant-scope">Answers are computed from the demo data for <strong>{viewLabel}</strong>, not generated by a model.</p>
          <div className="assistant-body">
            {everOpened && (
              <Suspense fallback={<AppLoading label="Loading assistant…" />}>
                <AssistantPanel key={resetCount} scope={scope} scopeLabel={scopeLabel} open={open} />
              </Suspense>
            )}
          </div>
        </section>
      </SidebarComponent>
    </>
  );
}
